[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "django-pony-express"
authors = [
    {'name' = 'Ambient Digital', 'email' = 'hello@ambient.digital'},
]
readme = "README.md"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 2.2",
    "Framework :: Django :: 3.1",
    "Framework :: Django :: 3.2",
    "Framework :: Django :: 4.0",
    "Framework :: Django :: 4.1",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Utilities",
]
dynamic = ["version", "description"]
license = {"file" = "LICENSE.md"}
dependencies = [
    'Django>=2.2.28',
    'html2text>=2020.1.16',
]


[project.optional-dependencies]
dev = [
   'pre-commit~=3.2',
   'black~=23.3',
   'Django~=3.2',
   'sphinx==4.2.0',
   'sphinx-rtd-theme==1.0.0',
   'm2r2==0.3.1',
   'mistune<2.0.0',
]

[tool.flit.module]
name = "django_pony_express"

[project.urls]
'Documentation' = 'https://django-pony-express.readthedocs.io/en/latest/index.html'
'Maintained by' = 'https://ambient.digital/'
'Bugtracker' = 'https://github.com/ambient-innovation/django-pony-express/issues'
'Changelog' = 'https://django-pony-express.readthedocs.io/en/latest/features/changelog.html'